# Generated by Django 5.0 on 2023-12-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmg_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.PositiveIntegerField(help_text='The category ID', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='num_of_products',
            field=models.PositiveIntegerField(help_text='Number of products in the category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(help_text='Product ID', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='supermarket_id',
            field=models.PositiveIntegerField(help_text='The supermarket id', primary_key=True, serialize=False, unique=True),
        ),
    ]
