# Generated by Django 5.0 on 2024-02-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmg_django_app', '0002_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterModelOptions(
            name='supermarket',
            options={'ordering': ['supermarket_name']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supermarket_id',
            new_name='supermarket',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='undefined', help_text='The name of each product.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(help_text='The category ID', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='supermarket_name',
            field=models.CharField(help_text='The supermarket name', max_length=50, unique=True),
        ),
    ]
