# Generated by Django 5.0 on 2023-12-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.PositiveIntegerField(help_text='The category ID', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(help_text='Category name', max_length=30, unique=True)),
                ('num_of_products', models.PositiveIntegerField(help_text='Number of products in the category', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('supermarket_id', models.PositiveIntegerField(help_text='The supermarket id', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('supermarket_name', models.CharField(help_text='The supermarket name', max_length=20, unique=True)),
                ('num_of_products', models.PositiveIntegerField(help_text='The total number of different products sold')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.PositiveIntegerField(help_text='Product ID', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('promotion_start_date', models.DateField()),
                ('promotion_end_date', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmg_django_app1.category')),
                ('supermarket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmg_django_app1.supermarket')),
            ],
        ),
    ]
